### ISSUE TITLE
Add a CSS reset

### ISSUE THREAD

**Issue by deletosh** [darkimpow/google-html#1]
@darkimpow let's add a new file called `reset.css` with a CSS reset  — see the context and code here: https://piccalil.li/blog/a-modern-css-reset/

**Comment by deletosh** [comment]
@darkimpow somethings to keep on mind:

1. This work should be part of the `feature/css-styling` branch
2. When you're adding the commit for this, add a comment as "fixes #1 - adds the reset.css file". Here's the magic that happens: https://github.blog/2013-01-22-closing-issues-via-commit-messages/

**Comment by darkimpow** [comment]
@deletosh Up to date

**Comment by deletosh** [comment]
@darkimpow your commit message should read "fixes #1 - adds the reset file" 

The key is that **fixes #1** — make a small change and add the new commit to [close this isse](https://github.blog/2013-01-22-closing-issues-via-commit-messages/)

**Comment by darkimpow** [comment]
@deletosh fixed issue #1 for reset file

**Comment by deletosh** [comment]
@darkimpow it should close it but I see why it didn't

**Comment by darkimpow** [comment]
completed
